namespace:
  name: prod

service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: igagankalra/techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

spec:
  containerPort: 3111
  resources:
    requests:
      cpu: 350m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  livenessProbe:
    httpGet:
      path: /healthz
      port: 3111
  readinessProbe:
    httpGet:
      path: /healthz
      port: 3111


