name: TechTrends - Package with Docker

# on:
  # workflow_run:
  #   workflows: ["Code Test"]
  #   types:
  #     - completed
on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Loging to DockerHub
        uses: docker/login-action@v1
        with:
          username: igagankalra
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}
      - 
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: igagankalra/techtrends:latest